- name: Debug all variables
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Dump reporting_thresholds
      debug:
        var: reporting_thresholds

    - name: Dump reporting_host_thresholds
      debug:
        var: reporting_host_thresholds

    - name: Dump hostvars for proxmox hosts
      debug:
        var: hostvars[item]
      loop: "{{ groups['proxmox'] }}"

